spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.253.128:3306/gulimall_pms?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 319e8753-ae7f-4e51-b499-49ffba57cdad
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    alicloud:
      #// 阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户
      access-key: LTAI5t5nX7uP56Syi77UhmTP
      secret-key: GXyCW87dC6nDS5Po4UpdCASzjRUUlU
      oss:
        #Endpoint以华东1（杭州）为例，其它Region请按实际情况填写。
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.253.128
    #host: 127.0.0.1
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000   #缓存的存活时间
      use-key-prefix: true
      #如果制定了缓存 的前缀 ，就用缓存的前缀作为缓存的名字  ， 没有制定前缀就用缓存的名字
      #key-prefix: CACHE_
      #是否缓存空值,防止缓存穿透的问题
      cache-null-values: true
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1  #表示逻辑删除
      logic-not-delete-value: 0 #表示逻辑不删除
server:
  port: 10000
logging:
  level:
    com.xqy.gulimall: debug
feign:
  hystrix:
    enabled: false
  client:
    config:
      gulimall-coupon:
        connectTimeout: 100000
        readTimeout: 100000


gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'

#seata:
#  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
#    # 参考tc服务自己的registry.conf中的配置
#    type: nacos
#    nacos: # tc
#      server-addr: 127.0.0.1:8848
#      namespace: "319e8753-ae7f-4e51-b499-49ffba57cdad"
#      group: DEFAULT_GROUP
#      application: seata-server # tc服务在nacos中的服务名称
#      cluster: default
#  tx-service-group: order-service # 事务组，根据这个获取tc服务的cluster名称
#  service:
#    vgroup-mapping: # 事务组与TC服务cluster的映射关系
#      order-service: default
#  data-source-proxy-mode: AT

