server:
  port: 5000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.253.128:3306/gulimall_oms?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 319e8753-ae7f-4e51-b499-49ffba57cdad
  application:
    name: gulimall-order
  rabbitmq:
    host: 192.168.253.128 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    #开启发送端确认机制
    publisher-confirms: true
    #开启发送端消息抵达队列确认机制
    publisher-returns: true
    #只要抵达队列，以异步的方式优先回调我们的returnCallback
    template:
      mandatory: true
    #消费端确认机制 手动ack
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  redis:
    host: 192.168.253.128
    #host: 127.0.0.1
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000   #缓存的存活时间
      use-key-prefix: true
      #如果制定了缓存 的前缀 ，就用缓存的前缀作为缓存的名字  ， 没有制定前缀就用缓存的名字
      #key-prefix: CACHE_
      #是否缓存空值,防止缓存穿透的问题
      cache-null-values: true
  session:
    store-type: redis
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
logging:
  level:
    root: info

seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 127.0.0.1:8848
      namespace: "319e8753-ae7f-4e51-b499-49ffba57cdad"
      group: DEFAULT_GROUP
      application: seata-server # tc服务在nacos中的服务名称
      cluster: default
  tx-service-group: order-service # 事务组，根据这个获取tc服务的cluster名称
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      order-service: default
  data-source-proxy-mode: AT

alipay:
  app_id: 9021000125616393
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCDb3aH/o1AfTjxn0UhtVkwb7akV2bSUslz6bqMq8eOfpD26BYU/gnBAUd7E5Ix/bLl0eAG63BFUn6wqWzFRUZr1vi3/XQTAm6eMidVAfc406QH+UTCQPiPMkDfIX+3i/KRL78Xwy3Nz3epR7dYKmnoQtES7Ei3LTN36TWq1Sxnm9bonhtKM4goxZMeaIf5u9AgazY1kpbFuwE7HcsHgEThWWVbYTzvvpiiWQTKJUOL1jVk2I3Cx3aYRtoIV4+MJ35GWpnxiBwbU9oXRMKKoPaJAIQwdItIs17IisKRJdUjKFNB3z+ghDeE0eA/0k9d5+lIgEqCzgu83CosFReQWDiRAgMBAAECggEADCKnfAj5u8GUF2MQO/uFf55g662SNcslBInJCqH1q+dttQ5as5d9CQ/4LJny/qCg+u001Q657/yc6+zIuTIbPWu8zSgepn6r/fk9fnDPBbUsyPuv6IudJ4OJT9DE/Qpz3Anfh+8idIU6VCvl9sL7wlEhArFESX1n6iNjLCHAltQ/mFKzvTzPfSGhfJ8wmuBk2tTvDdCBMWTrexP/hc3JoLIu++PJLfAR72KcZ/H5RH4GbdbZoDtVbak7YLbNyXL8RYk+a4ZhU9gUDUBtbFVU7l3Me4B3l5lXVi+jbt43nBj6G/EcCx4PrQA+0TafrdiED08m+44W9tGLhR0WAadDUQKBgQDOdGefPcD6outkKxfCs3DtVUCLenloCUAnB0Zd/HVsaCktnfcQhuKafXMTX+d/etPkYxpWcc8lISp5DxJ8lkS7Wzm1AqJHRMnP+xQOrcSsWUrYWnuKwzq2FD8xihMRJNV+Hz0e7p0+L13WcHL1cBYhkudMOfTjZU+elcoP3WFInQKBgQCi+jqgxhFM7CVLaZPRVEvT+gJwD8YBrvqq0ZWSHMxW/ktZn++74nB0HodwGeJU0kwwGQAGs7dkKkutK8bZ1dOgldujtJtrZj0222XaoEmD8sGxXYbPsjwpokX/gyHkLQF3o99DFLojIWs/A06PV8pWi568Fh56FUZNHS9FhU3LhQKBgQC1iJFc6hX3zK2iRGn+H35aka3Rdv2txwSLzM/I8KXnjqc2n0GRXKmAInK/RILwCvaqSaHtBOGZylHoZKJivlbtT0esrAY5GHlD0YhPZ+gZi+JN3zHmT8geNitiyf/+AR9gaON7gWDuPwQJ/JJ40fgDyYJr+kIkeP7LePZVgNl72QKBgBds+Dhbv+jamJG6XzDbePrDGM6atc9QI1+iOGmEEir+6j27q23KInfOW5FVZx7iC2lubn6IHngbTD1b6X0uKvkOET/6mcxaKbpU1tMR7v80SXsBAnugFt21IXKUmq59eZSEzXaK6CZci1nHU+duqvq9ntdSJpdNr4kuBLlta70xAoGBAMRZkYsaYqi0t8kl33JcqPaOcMynD+RSfs1tnlAnCiut9PTj8lz+bfPDqaPjXxsD8QVf8uhxzJf7OiDXnB2VS9uC+jBK5jqLko93CrbwHKm5II2cRrJq102jzg1uyiZ48e9PRQWa2/WtB/Xidl/upBvfd6bjKcZngbZwP+XaxuQR
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhc8qgrvcEl0y+V601YidWwWnhnRvF/y2+Tm5vnqktv6KiF/FNm00ZmQhCnzRwPZa49VfZPhzAThoNVOY9ghQjo8rZDaGHf8C5G79TZiBrWn5VXUk8JIQZ8N0cSKxwLslhtb2hunuwQzWohINigKApSWGaIBJbJNesF1qT4YAzmaf0bzPUMsnZ3/rfIreyNPN5F0OPv+ueQW4PCRNedPzco/LhWE7IaoySlgp22xM77MpOzRoDjFk6uqQydPKMJ/r2WnkE4YCB787UhSVWJrZ0Or+kmVCe4DL6k7DWd73nNzvrKdpt8yIyatoiXvScVsV7Os87x7gifvcDa0ylHK3QQIDAQAB
  notify_url: http://vve2t6.natappfree.cc/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  timeout: 10m
