spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 319e8753-ae7f-4e51-b499-49ffba57cdad
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    alicloud:
      #// 阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户
      access-key: LTAI5t5nX7uP56Syi77UhmTP
      secret-key: GXyCW87dC6nDS5Po4UpdCASzjRUUlU
      oss:
        #Endpoint以华东1（杭州）为例，其它Region请按实际情况填写。
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
      #短信验证服务
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        method: POST
        appcode: 061fb5a334e647d282b9c3fccb01b03e
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: a09602b817fd47e59e7c6e603d3f088d
  application:
    name: gulimall-third-party

server:
  port: 30001
logging:
  level:
    com.xqy.gulimall: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'